# Generated by Django 4.0.2 on 2022-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conturi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adresa',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profil',
            name='localitate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
