# Generated by Django 4.0.2 on 2022-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conturi', '0002_alter_profil_adresa_alter_profil_localitate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profil',
            name='localitate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nr_telefon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profil',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
