# Generated by Django 4.0.2 on 2022-08-25 10:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('conturi', '0003_alter_profil_adresa_alter_profil_localitate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='nr_telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
