# Generated by Django 4.0.2 on 2022-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conturi', '0004_alter_profil_nr_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='statut_UserAprobat',
            field=models.BooleanField(default=False),
        ),
    ]
