# Generated by Django 4.0.2 on 2022-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conturi', '0005_profil_statut_useraprobat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
