# Generated by Django 4.0.2 on 2022-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordonator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alegere',
            options={'verbose_name_plural': 'Alegeri'},
        ),
        migrations.RenameField(
            model_name='alegere',
            old_name='status',
            new_name='status_Alegere',
        ),
    ]
