# Generated by Django 4.0.2 on 2022-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='mesaj',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='subject',
            new_name='subiect',
        ),
    ]
