# Generated by Django 4.0.2 on 2022-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_message_feedback_mesaj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'verbose_name_plural': 'Candidați'},
        ),
    ]
